# general
gpu_id: 0
use_gpu: True
seed: 2020
state: DEBUG
reproducibility: True
data_path: '/home/guedes-joaofelipe/Workspace/RecommenderSystem/datasets/'
checkpoint_dir: 'saved'
show_progress: True

# evaluation settings
sparsity_quantiles: [.25, .5, .75, 1.]
sparsity_filter: 'gini'
eval_setting: RO_RS,full
group_by_user: True
split_ratio: [0.8,0.1,0.1]
leave_one_num: 2
real_time_process: False
metrics: ["Recall","MRR","NDCG","Hit","Precision"]
topk: [10]
valid_metric: MRR@10
valid_metric_bigger: True
eval_batch_size: 4096
loss_decimal_place: 4
metric_decimal_place: 4
